services:
  
  # Backend Service
  virtual_store_backend:
    container_name: virtual_store_backend
    build: .
    restart: always
    ports:
      - '${PORT}:3000'
    depends_on:
      - virtual-store-db
  
  # MySQL Database
  virtual-store-db:
    container_name: virtual_store_database
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '${PORT_DATABASE}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
